# SQLite version 3.x
#   gem install sqlite3
development:
  adapter: mysql2
  database: twit
  username: root
  password: root
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  database: twit_production
  username: root
  password: root
  pool: 5
  timeout: 5000